### PR TITLE
Add post for getfeature WFS 1.1.0 and 2.0.0

### PR DESCRIPTION
**Pull request by f-PLT**
Doing this PR here first, since it's been done for the needs of our projects.

Added support for the Post method, both for 1.1.0 and 2.0.0.

Also added the ability to use an existing xml filter as is. Might be redundant, but it's only 2 lines of code.

featureversion, storedQueryID and storedQueryParams arguments have not been implemented for the post method, as I was not sure how to implement or if there are added benefits for their availability via Post.

One part I am not sure about: https://github.com/f-PLT/OWSLib/blob/wfs-getfeature-post/owslib/feature/__init__.py#L309

```
try:
            base_url = next(
                (
                    m.get("url")
                    for m in self.getOperationByName("GetFeature").methods
                    if m.get("type").lower() == method.lower()
                )
            )
        except StopIteration:
            base_url = self.url
```

I used the above for the Post method, taken from the Get implementation. In some cases however, like with the Boreas server, the request failed using the found url, but worked if I only used `base_url = self.url`. I think with Post, there is no redirection to _https_ or it behaves differently than Get? 

It could have an impact on how we configure and secure our Geoservers when we want to give access to them to outside collaborators. Not sure how much of an issue this is.

The PR looks cluttered, but a pull from owslib/master to our fork should clean up things (which I can't do myself because of permissions). The main files to look at are `owslib/feature/__init__.py` and `owslib/feature/postrequest.py`

### CODE REVIEW

**Comment by huard** [comment]
@cehbrecht The birdhouse master has a conflict with the upstream master. Should I do something like: 
```
git reset --hard upstream/master
git push 
```

**Comment by cehbrecht** [comment]
> @cehbrecht The birdhouse master has a conflict with the upstream master. Should I do something like:
> 
> ```
> git reset --hard upstream/master
> git push 
> ```

@huard you can do so ... otherwise we don't need to keep a fork of owslib in birdhouse anymore.

**Comment by cehbrecht** [comment]
> > @cehbrecht The birdhouse master has a conflict with the upstream master. Should I do something like:
> > ```
> > git reset --hard upstream/master
> > git push 
> > ```
> 
> @huard you can do so ... otherwise we don't need to keep a fork of owslib in birdhouse anymore.

ah ... the owslib PR goes to birdhouse. If we want to keep a fork for dev, I usually have the master in sync with the upstream and use a branch for the changes.

**Comment by huard** [comment]
How do you keep the two masters in sync ? Manually ?

**Comment by fmigneault** [comment]
> 
> 
> How do you keep the two masters in sync ? Manually ?

Yes, you would need to pull geopython/OWSLib master into this master.

**Comment by fmigneault** [comment]
> featureversion, storedQueryID and storedQueryParams arguments have not been implemented for the post method, as I was not sure how to implement or if there are added benefits for their availability via Post.

According to http://www.opengis.net/doc/IS/wfs/1.1.3: 

> If versioning is supported, the FEATUREVERSION parameter directs the WFS on which feature version to fetch..  A value of ALL indicates to fetch all versions of a feature.  An integer value fetches the Nth version of a feature.  No value indicates that the latest version of  the feature should be fetched. 

So there should always be filtering of the latest unless specified not to.

For the stored query params, it should be only WFS 2.0.0 + it should drop the filter as it effectively "loads" the stored arguments to re-use. (www.opengis.net/doc/IS/wfs/2.0)
As described here: 

https://github.com/geopython/OWSLib/blob/8a94500c2137082dfc4e59acd15389312bcb63fb/owslib/feature/wfs200.py#L273-L278

**Comment by huard** [comment]
@f-PLT I updated the master.

**Comment by f-PLT** [comment]
Hmm, the commits aren't changing to reflect the changes in the master.

If we take the approach of @cehbrecht , a branch could be created and I could edit the PR to point to that branch?

I added _featureversion_. From what I understand, it's simply an argument to the Query element.

As for StoredQuery, I'll start working on it, I think I found an example to start from.

**Comment by fmigneault** [comment]
> Hmm, the commits aren't changing to reflect the changes in the master.

try pulling master into your branch and push the merged commit

**Comment by f-PLT** [comment]
Following a discussion with @huard , I'll be closing this PR and making a new one to the OWSLib repo once I've finished adding StoredQuery.

**Pull request closed without merging**
